hexpm/hex

lib/hex.ex, lib/mix/tasks/hex/config.ex, lib/mix/tasks/hex/user.ex
This pull request allows users to set the following configuration settings from the config file:
- API URL
- CDN URL
- HTTP proxy
- HTTPS proxy
>Note: Sadly, setting the home directory from the config file is impossible.
This allows users to do the following:
```shell
$ mix hex.config api_url http://hex.internal.corporation.com
$ mix hex.config cdn_url http://cdn.hex.internal.corporation.com
```
:christmas_tree: :fireworks: Merry Christmas and a Happy New Year!
=> Allow setting CDN, API URL and HTTP proxy settings in Hex config

lib/mix/tasks/hex/docs.ex
Closes #72 
Changes:
- allows for both `doc/` and `docs/` documentation directories
- raises an error when documentation directory is unavailable
- alerts ex_doc users that they can update to the latest release that will prefer `doc/`
/cc @josevalim 
:page_with_curl:
=> Prefer doc/ for documentation.

lib/hex/api/user.ex, lib/mix/tasks/hex/user.ex, test/hex/api_test.exs, test/mix/tasks/hex/user_test.exs
Related to hexpm/hex_web#89;
Changes:
- Adds the mix task `mix hex.user reset`. This accepts either a username *or* email address belonging to an account.
- Removes `mix hex.user reset`
:closed_lock_with_key: :key:
=> Add 'mix hex.user reset'; remove 'mix hex.user update'

lib/mix/tasks/hex.ex
This is in reference to #79. It adds a root task to hex (e.g. `mix hex`)
The output is as follows:
Elixir <1.1.0:
```shell
$ mix hex
Hex v0.7.2-dev
Hex is a package manager for the Erlang ecosystem.
Further information can be found here: https://hex.pm/docs/tasks
```
Elixir >=1.1.0
```shell
$ mix hex
Hex v0.7.2-dev
Hex is a package manager for the Erlang ecosystem.
Available tasks:
mix hex.config  # Read or update hex config
mix hex.docs    # Publish docs for package
mix hex.info    # Print hex information
mix hex.key     # Hex API key tasks
mix hex.owner   # Hex package ownership tasks
mix hex.publish # Publish a new package version
mix hex.search  # Search for package names
mix hex.user    # Hex user tasks
Further information can be found here: https://hex.pm/docs/tasks
```
Output is …
=> Add root task (mix hex)

lib/hex/remote_converger.ex, lib/hex/resolver.ex
I have been thinking for a long time on how we can give good error messages when the dependency resolution fails. It's very tricky to do because of the resolution algorithm we use (we try every possible combination of all packages, with some shortcuts and optimizations). Because of this we cannot directly tell the user where the resolution failed (there were potentially many failures that we backtracked from) or how to fix it.
The approach I do here is to print every time we backtrack and say on which package we backtracked on and why. The advantage of this approach is that if resolution failed we will always print why. The drawback is that the backtracks can be hard for users to understand (looking for feedback on this) and if you have many unlocked dependencies and is unlucky there can …
=> WIP: Better error messages when dependency resolution fails

lib/mix/tasks/hex/outdated.ex, test/mix/tasks/hex/outdated_test.exs
Note: I don't think this is ready for merging yet, but I'd love to get some feedback.
This is a task that:
Shows all packages that have a version mismatch between the
hex.pm registry and your mix.lock file.
`mix hex.outdated`
I mainly wrote it because it's a pain to check out hex.pm for every package that I have in my mix.exs every other day to see if something was updated.
This will only print out packages that are specified as a top-level dependency.
The output looks like:
```
ecto is outdated. Latest is 0.10.0, your mix.lock specifies 0.9.0.
kalecto is outdated. Latest is 0.2.1, your mix.lock specifies 0.1.2.
kalends is outdated. Latest is 0.6.1, your mix.lock specifies 0.5.2.
```
The other thing I was having trouble with was how I could write a test for this feature... Any tips would …
=> Mix task for hex.outdated.

lib/hex/api.ex, lib/hex/registry.ex, lib/hex/util.ex, test/hex/registry_test.exs
As *TODO*ed in f006fda.
Adds function `Hex.Util.yellow_error`, which does as it describes: Formats a Mix.shell.error to be displayed in yellow.
=> Add support for yellow error messages

lib/hex/remote_converger.ex
Fixes typo in 7ab3426, as shown [here](https://github.com/hexpm/hex/commit/7ab342663dd5e1818b9b7b1464c1bc505ecfa62f#diff-2a62a3004b2824bb336a176595988caaR41) (`HexShell` --> `Hex.Shell`)
:apple:
=> Fix typo in Remote Converger

lib/mix/tasks/hex/publish.ex, test/mix/tasks/hex/publish_test.exs
Took a stab at #105, just to get a feeling of Hex's codebase so that I can try to be more helpful in the future :). Let me know what you think, thanks!
=> Print a link to the CoC when publishing packages

lib/hex/resolver.ex, test/hex/resolver_test.exs
Addresses #109.
I used `ExUnit.CaptureIO` to test this as I developed, but removed it because I wasn't sure what the policy was on testing user-facing output. Testing the output also required some reworking of unrelated test code.
I'm happy to add the test code back in and test the output of the other error messages in this PR or in a separate one. Let me know.
=> improve locked dep error message

lib/mix/hex/utils.ex, lib/mix/tasks/hex/build.ex, lib/mix/tasks/hex/docs.ex, lib/mix/tasks/hex/key.ex, lib/mix/tasks/hex/owner.ex, lib/mix/tasks/hex/publish.ex, lib/mix/tasks/hex/user.ex
As discussed briefly with @lexmag in #129, this is a small follow-up PR to move `mix/tasks/hex/utils.ex` into `mix/hex/utils.ex` for consistency. This way, all files inside `mix/tasks/` will be hex tasks.
=> move mix/tasks/hex/utils.ex to mix/hex/utils.ex

README.md, lib/hex/parallel.ex, lib/hex/registry.ex, lib/mix/tasks/hex.ex, lib/mix/tasks/hex/build.ex, lib/mix/tasks/hex/config.ex, lib/mix/tasks/hex/docs.ex, lib/mix/tasks/hex/info.ex, lib/mix/tasks/hex/key.ex, lib/mix/tasks/hex/outdated.ex, lib/mix/tasks/hex/owner.ex, lib/mix/tasks/hex/publish.ex, lib/mix/tasks/hex/search.ex, lib/mix/tasks/hex/user.ex
this is mainly to have a unified `mix help` command,
and also when we do `mix help TASK`
It introduces the latest standardization in the Elixir codebase
=> Standardize docs

lib/mix/hex/build.ex, lib/mix/tasks/hex/publish.ex, test/mix/tasks/hex/build_test.exs, test/mix/tasks/hex/publish_test.exs
Related to discussion in: https://github.com/hexpm/hex_web/pull/166 and https://github.com/hexpm/hex_web/issues/162
Notes:
- Not sure about all the checks in ```raise_if_missing_description!/1```. 
- I got a bit creative with the error message. :) Happy to change it if needed.
=> Raise error if package description is missing

lib/hex/api.ex, lib/hex/scm.ex, lib/hex/utils.ex, test/hex/utils_test.exs
This PR ensures that calls to `:httpc.request` using the `:hex` profile supply `proxy_auth` as a `http_option()`
My use case is deploying elixir apps to an internal deployment of Cloud Foundry behind a firewall, limiting external connections to proxies. Hopefully others will find this useful!
=> Ensure http proxy authentication is supplied in httpc calls

lib/mix/tasks/hex/docs.ex
Related to: https://github.com/hexpm/hex/issues/155
I made the message as a warning. Is this okay or should I change it to  `Hex.Shell.info` ?
=> Suggest adding ex_doc if docs task is missing when running hex.docs

lib/mix/tasks/hex/info.ex, test/mix/tasks/hex/info_test.exs, test/test_helper.exs
This PR changes first string on `mix hex.info {package_name}` command output.
Example of output
```
$ mix hex.info httpoison
{:httpoison, "~> 0.8.0}
Releases: 0.8.0, 0.7.5, 0.7.4, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.2, 0.6.1, 0.6.0, 0.5.0, 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.2, 0.3.1, 0.3.0, 0.2.0
Maintainers: Eduardo Gurgel Pinho
Licenses: MIT
Links:
Github: https://github.com/edgurgel/httpoison
Yet Another HTTP client for Elixir powered by hackney
```
=> Change mix hex.info package output

lib/mix/tasks/hex/info.ex, test/mix/tasks/hex/info_test.exs, test/test_helper.exs
Closes #171.
```elixir
Yet Another HTTP client for Elixir powered by hackney
Config: {:httpoison, "~> 0.8.0"}
Releases: 0.8.0, 0.7.5, 0.7.4, 0.7.3, 0.7.2, 0.7.1, 0.7.0, 0.6.2, 0.6.1, 0.6.0, ...
Maintainers: Eduardo Gurgel Pinho
Licenses: MIT
Links:
Github: https://github.com/edgurgel/httpoison
```
```elixir
Config: {:httpoison, "~> 0.7.2"}
Documentation at: http://hexdocs.pm/httpoison/0.7.2/
Dependencies:
hackney: ~> 1.3.1
```
=> Refine hex.info task output

lib/hex/remote_converger.ex, test/hex/mix_task_test.exs
Introduced in b2937c181295653559dad5c0d5eacd5ed7e16baa
This crashes hex on missing dependency requirement.
=> Fixed typo: Hex.shell => Hex.Shell

lib/hex.ex, lib/hex/mix.ex, lib/hex/registry.ex, lib/hex/remote_converger.ex, lib/hex/resolver.ex, lib/hex/resolver/backtracks.ex, lib/hex/resolver/experimental.ex, lib/hex/state.ex, lib/hex/version.ex, lib/mix/tasks/hex.ex, lib/mix/tasks/hex/info.ex, lib/mix/tasks/hex/outdated.ex, test/hex/resolver_test.exs, test/support/case.ex
The following dependencies shows performance problems in the resolver:
```elixir
[{:phoenix, "~> 0.14"},
{:phoenix_ecto, "~> 0.5"},
{:postgrex, ">= 0.0.0"},
{:phoenix_html, "~> 1.1"},
{:phoenix_live_reload, "~> 0.4"},
{:cowboy, "~> 1.0"}]
```
Before this PR resolving the dependencies would take ~15min and use several GB of memory with OTP 18.2.1 and Elixir 1.2.1 on a Macbook Pro Late 2013. After this PR it takes ~1min40sec and uses ~50mb of memory.
Some of the wins comes from caching values in ETS that are recalculated a lot. Most of the wins including the memory reduction comes from moving the backtrack store from an Agent to ETS and immediately removing duplicates.
I am stuck right now because I think that reducing the current time will require algorithm changes and I don't know how to …
=> Performance improvements

.travis.yml, test/support/hex_web.ex
hex_web is used as an API server to integration test against. This PR allows us to test the hex client with any elixir and otp version without it affecting the versions hex_web use of elixir and otp.
=> Run hex_web with custom elixir and OTP version on travis

test/hex/mix_test.exs
This tests shows that a child should not be included in the flattened
dependencies if it not specified in the deps list.
=> tests(Hex.Mix): add tests for flatten_deps

test/hex/mix_test.exs
The names of the dependencies have been renamed to actual libraries so
that the tests are easier to understand.
=> tests(Hex.Mix): add tests for overriding dependencies

lib/mix/tasks/hex/search.ex, test/mix/tasks/hex/search_test.exs
Instead of throwing an Enum.EmptyError, return a message about no packages found.
=> Catch an empty search result

lib/hex/version.ex
Before:
```
iex(1)> Hex.Version.parse! "0.0.1"
#Version<0.0.1>
iex(2)> Hex.Version.parse! "0.0.1a"
** (UndefinedFunctionError) undefined function InvalidVersionError.exception/1 (module InvalidVersionError is not available)
InvalidVersionError.exception([message: "0.0.1a"])
(hex) lib/hex/version.ex:39: Hex.Version.parse!/1
```
```
iex(3)> Hex.Version.parse_requirement! "0.0.1" 
#Version.Requirement<0.0.1>
iex(4)> Hex.Version.parse_requirement! "0.0.1a"
** (UndefinedFunctionError) undefined function InvalidRequirementError.exception/1 (module InvalidRequirementError is not available)
InvalidRequirementError.exception([message: "0.0.1a"])
(hex) lib/hex/version.ex:57: Hex.Version.parse_requirement!/1
```
After:
```
iex(1)> Hex.Version.parse! "0.0.1"
#Version<0.0.1>
iex(2)> Hex.Version.parse! …
```
=> Fix errors raised when parsing invalid version/requirement

lib/mix/tasks/hex/publish.ex, test/mix/tasks/hex/publish_test.exs
today in the elixir mastery class we found that the code of conduct links were no longer correct. this should update them to the correct endpoints.
=> update code of conduct links

lib/hex/registry.ex
Simple fix. Just noticed that "against" was used twice when displaying a warning message.
=> Quick Error Message Fix

lib/mix/hex/build.ex, test/mix/tasks/hex/build_test.exs, test/support/release_samples.ex
Warns the user during `mix hex.publish` if the package description exceeds 300 characters.
Fixes #229 :grin:
=> Warn about long package descriptions

test/support/hex_web.ex
This should fix hex_web build, see failure: https://travis-ci.org/hexpm/hex_web/builds/137178925.
Not sure why CI didn't catch this. When I tried cloning hex locally and running tests on v1.2.1, it did fail with the same error though.
=> Fix build on Elixir < 1.3

lib/mix/hex/build.ex, test/mix/tasks/hex/publish_test.exs, test/support/release_samples.ex
WIP. This needs to get tracked alongside associated commits in hex_web.
The idea is that we would like to allow passing extra metadata about the package which can be searched upon using the search api on hex_web.
For example, 
```elixir
defmodule ReleaseMeta.Mixfile do
def project do
[app: :release_c, version: "0.0.3",
description: "foo",
package: [files: ["myfile.txt", "missing.txt", "missing/*"],
licenses: ["Apache"],
links: %{"a" => "b"},
maintainers: ["maintainers"],
extra: %{"bar" => "baz"}]]
end
end
```
It seems that in order to apply a search index to additional meta keys, we would have to apply it to a known key like `:extra`. This also reduces complexity of the top level spec. 
To search this data we would construct a search path like path: "extra/bar", search: "baz". 
Tracked …
=> Allow extra searchable metadata in package

lib/mix/tasks/hex/key.ex, lib/mix/tasks/hex/outdated.ex, lib/mix/tasks/hex/owner.ex, lib/mix/tasks/hex/registry.ex, lib/mix/tasks/hex/user.ex
I want to remove "tasks" from the shortdoc because it's redundant but not sure if this is an improvement.
/cc @josevalim
=> Improve task shortdocs

lib/hex/api/key.ex, lib/mix/tasks/hex/key.ex, test/hex/api_test.exs, test/mix/tasks/hex/key_test.exs, test/support/hex_web.ex
This pull request should hopefully resolve #251, #252, and #253.
**Note:** These changes are dependent on pull requests #255 and hexpm/hex_web#378, so I expect travis to throw a fit over the tests.
1. Support for `mix hex.key remove --all` added (see #251)
2. If the current key is being removed from the server, the key is also removed from the local configuration (see #253)
3. An error message is displayed to the user if their key has been revoked (see #252)
1. Removing the current key from the server has the same effect as `mix hex.key remove KEY` followed by `mix hex.user deauth`.  There's nothing really left in the config file related to authentication other than `username` at that point.
2. There is no global handling for the "API key revoked" error sent back from the server.  Would …
=> Support for revocation of all keys and removal from local config

lib/hex/api.ex, test/hex/resolver_test.exs, test/mix/tasks/hex/user_test.exs
I've been told we were getting a tad too many warnings because of `Dict` here on hex 😛
=> Remove all references to Dict (which is deprecated)

lib/mix/tasks/hex/outdated.ex, test/mix/tasks/hex/outdated_test.exs
If someone runs the `hex.outdated` task and the application do not depend on any Hex package, show a proper message.
```
==> app_one
Dependency  Current  Latest  Requirement
A green version in latest means you have the latest version of a given package. A green requirement means your current requirement matches the latest version.
```
```
==> app_one
Hex Dependencies: None
```
=> Do not show table when app do not have Hex deps

lib/mix/tasks/hex/outdated.ex
* umbrella project depends on: `{:ex_doc, "~> 0.13"}`
* sub-project `apps/app_one` depends on: `{:bupe, github: "owner/repo"}`
* sub-project `apps/app_two` depends on: `{:plug, "~> 1.0"}`
```bash
$ cd ~/umbrella
$ mix hex.outdated
Dependency  Current  Latest  Requirement
ex_doc      0.13.0   0.13.0  ~> 0.13
A green version in latest means you have the latest version of a given package. A green requirement means your current requirement matches the latest version.
$ mix hex.outdated --all
Dependency  Current  Latest  Requirement
earmark     1.0.1    1.0.1   ~> 1.0
ex_doc      0.13.0   0.13.0  ~> 0.13
plug        1.1.6    1.1.6   ~> 1.0
A green version in latest means you have the latest version of a given package. A green requirement means your current requirement matches the latest …
```
=> List root dependencies in umbrella projects

lib/mix/hex/build.ex, test/mix/tasks/hex/build_test.exs, test/mix/tasks/hex/publish_test.exs, test/support/release_samples.ex
The idea of this PR is working on converting all the current warnings in the package building and publishing process into errors. @ericmj Please let me know what do you think.
Fixes: #267
=> [WIP] Convert all warnings when building a pkg on errors

lib/hex/state.ex
Adding `Kernel.not` negation as per request
=> Negating HEX_UNSAFE_REGISTRY value #285

lib/mix/tasks/hex/docs.ex, test/mix/tasks/hex/docs_test.exs
hex.docs open will go online to hexdocs.pm
unless --offline option is specified.
fix #291
=> Adding --offline option to hex.docs open

lib/mix/tasks/hex/docs.ex
Took a stab at #290 
With this implementation, the task checks if the documentation for the package is locally present. Otherwise, it will fetch the latest version and open it in the browser.
=> Modify hex docs.open to fetch docs if not present locally

lib/hex/scm.ex, test/hex/scm_test.exs
After the last changes the backwards compatibility with Elixir 1.0.x versions has been accidentally broken.
Changing `MapSet.new` to the already existing `Hex.Set.new` wrapper should fix that.
This was the actual error message I encountered:
```
** (UndefinedFunctionError) undefined function: MapSet.new/1 (module MapSet is not available)
MapSet.new(["CHANGES.md", "LICENSE", "mix.exs", "rebar.config", "README.md"])
(hex) lib/hex/scm.ex:142: Hex.SCM.guess_build_tools/1
(hex) lib/hex/scm.ex:111: Hex.SCM.checkout/1
(mix) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
(mix) lib/mix/dep/converger.ex:154: Mix.Dep.Converger.all/8
(mix) lib/mix/dep/converger.ex:163: Mix.Dep.Converger.all/8
(mix) lib/mix/dep/converger.ex:47: Mix.Dep.Converger.converge/4
(mix) lib/mix/dep/fetcher.ex:16: …
```
=> Fix elixir 1.0.x compatibility

lib/mix/tasks/hex/docs.ex
=> hex.docs now opens with xdg-open for non OSX unix systems

lib/mix/tasks/hex/search.ex, test/mix/tasks/hex/search_test.exs
This restores the behavior of printing out the latest version of each matching package. This used to be implemented, but was removed during some v2 refactoring.
=> Restore including latest version with hex.search

lib/hex/utils.ex, lib/mix/tasks/hex/docs.ex
As discussed at #315 adding `--module` flag for opening specified module documentation
=> Add --module flag to hex.docs task

CHANGELOG.md, lib/mix/tasks/hex/outdated.ex, test/mix/tasks/hex/outdated_test.exs, test/test_helper.exs
It now takes all dependent packages into account and simply prints a `Yes` or a `No` for outdated packages.
Fixes #322
The added test would show with a green "Requirement" before this update, even though it can't be updated.
=> Changed hex.outdated to show if a dependency can be updated

lib/hex/api.ex, lib/hex/api/verify_hostname.ex, lib/hex/mix.ex, lib/hex/resolver/backtracks.ex, lib/hex/scm.ex, lib/hex/utils.ex, lib/mix/hex/build.ex, test/mix/tasks/hex/docs_test.exs, test/support/hex_web.ex
As @ericmj's [suggested](https://github.com/hexpm/hex/pull/336#pullrequestreview-14419850), we should use one pipe operator per line.
I excluded the file `lib/hex/state.ex` because I think the code is clear the way it is, wdyt?
=> Normalize usage of one pipe per line

lib/mix/tasks/hex/key.ex, lib/mix/tasks/hex/user.ex, test/mix/tasks/hex/key_test.exs, test/mix/tasks/hex/user_test.exs
Fixes: #305 /cc @josevalim @ericmj
=> Move hex.key tasks to hex.user

lib/mix/tasks/hex.docs.ex, lib/mix/tasks/hex.install.ex
To be in accordance with the format used in Elixir
=> Use present continuous in @moduledoc summaries and @shortdocs

lib/mix/tasks/hex.build.ex, test/mix/tasks/hex.build_test.exs, test/support/release_samples.ex
Took a quick shot at #320 and I'd like some feedback because I think it needs more polishing. Also, should it throw an error or just show a warning? Fire away! 😃
=> Throw error if publishing a non-pre package that has pre-dependencies

lib/mix/tasks/hex.repo.ex, test/mix/tasks/hex.repo_test.exs
Fixes https://github.com/hexpm/hex/issues/363.
When repo is found:
```sh
$ mix hex.repo show hexpm
URL                  Public key                                          Auth key
https://repo.hex.pm  SHA256:O1LOYhHFW4kcrblKAxROaDEzLD8bn1seWbe5tq8TRsk
```
When repo is not found:
```sh
$ mix hex.repo show somerepo
** (Mix) Config does not contain repo somerepo
```
=> Add hex.repo subtask to show repo config

README.md, RELEASE.md
Docs mention including integration tests but they are already included by default.
Discussion here: https://github.com/hexpm/hex/issues/379
=> Update docs to match tests code

lib/hex/remote_converger.ex, lib/hex/scm.ex, test/hex/mix_task_test.exs
The goal of this PR is to avoid complete rewrites of the lock file when the lock tuples format changes.
This first commit achieves this for `mix deps.get` when the dependencies are already pulled (nothing changes in the lock file), and for `mix deps.update` (only the updated dependencies change in the lock file).
It doesn't work when doing `mix deps.get` when the `deps` folder is not present (the lock file is rewritten), a little guidance on where to look to fix this would be appreciated :)
=> More granular lock files updates

lib/hex/scm.ex
When you use a private repo with the basic authentication, `mix deps.get` reveals the password.
```
* Updating some_thing (Hex package)
Checking package (https://username:password@private.repo.example.com/path/some_thing-0.1.2.tar)
```
This PR replaces the password part with `******`.
```
* Updating some_thing (Hex package)
Checking package (https://username:******@private.repo.example.com/path/some_thing-0.1.2.tar)
```
=> Hide basic authentication password from the message.

lib/hex/remote_converger.ex, lib/hex/utils.ex, lib/mix/tasks/hex.audit.ex, test/mix/tasks/hex.audit_test.exs
This PR resolves #375.
As per the issue, the `hex.audit` task searches for packages that are locked to retired versions. If they're found, the task lists them and exits with an error code (1).
Here's sample output:
Package retirement reasons (`RETIRED_INVALID`, `RETIRED_SECURITY`, etc.) were mapped to corresponding text messages inside a private function in Hex.RemoteConverger. I've moved it to Hex.Utils to be able to use it inside the task, but I'm not sure if that's the right place for it.
I may have missed some other important details, too, so any feedback is appreciated :smiley:
=> Add hex.audit

lib/mix/tasks/hex.publish.ex
In the spec [1] we've made `html_url` required, however I can see it being optional too. I imagine someone could build a hex custom repo with just APIs and no HTML stuff. If we make it optional, we still need to display some URL when package is published, so I think falling back to API url is reasonable.
This really is only an issue when we allow publishing packages to non-hexpm repos, however leaving it here as a mental note :)
[1] https://github.com/hexpm/specifications/pull/21/files#diff-2625016b50d68d922257f74801cac29cR313
cc @asgoel
=> Make html_url optional

mix.exs, test/fixtures/ecto/mix.exs, test/fixtures/ex_doc/mix.exs, test/fixtures/has_hex_dep/mix.exs, test/fixtures/override_with_path/mix.exs, test/fixtures/sample/mix.exs, test/hex/mix_task_test.exs, test/mix/tasks/hex.audit_test.exs, test/mix/tasks/hex.build_test.exs, test/mix/tasks/hex.outdated_test.exs, test/mix/tasks/hex.publish_test.exs, test/support/hexpm.ex, test/support/release_samples.ex
Mix renames the module in `mix.exs` file from `Mixfile` to `MixProject`.
This pull request updates the name.
Reference: https://github.com/elixir-lang/elixir/commit/c6a0edcd32359eca284ff0166d19a6dc979ee954
=> Use MixProject instead of Mixfile in mix.exs files

lib/mix/tasks/hex.docs.ex
When executes `hex.docs fetch` Mix task with a package version that does not exist, raises a `MatchError` exception.
Example:
```zsh
% mix hex.docs fetch elixir 1.3.5
** (MatchError) no match of right hand side value: {:ok, {403, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>B94CAE1A61603FE2</RequestId><HostId>80EI0mEDxzmDBdL3eRU5wbVenHgXsiJ0/KWO7kpk45Eeeg7dCa2sB/5T4XEyrq1pF4977wciXGY=</HostId></Error>", %{'accept-ranges' => 'bytes', 'connection' => 'keep-alive', 'content-length' => '243', 'content-type' => 'application/xml', 'date' => 'Sat, 26 Aug 2017 06:29:29 GMT', 'server' => 'AmazonS3', 'via' => '1.1 varnish', 'x-amz-id-2' => '80EI0mEDxzmDBdL3eRU5wbVenHgXsiJ0/KWO7kpk45Eeeg7dCa2sB/5T4XEyrq1pF4977wciXGY=', …
```
=> Handle package documentation mirror response

test/mix/tasks/hex.organization_test.exs
It appears this test file may be missing the "integration" tag. It fails when run without the local server up.
=> Add "integration" tag to hex.organization_test.exs

lib/hex/registry/server.ex
I noticed today that when I run `mix deps.get` when my wifi is down I get all of this:
```
± > mix deps.get                                                                                                                -I-
Failed to fetch record for 'hexpm/connection' from registry (using cache)
** (exit) exited in: GenServer.call(Hex.Registry.Server, {:versions, "hexpm", "connection"}, 60000)
** (EXIT) an exception was raised:
** (FunctionClauseError) no function clause matching in Hex.Registry.Server.missing_status?/1
(hex) lib/hex/registry/server.ex:365: Hex.Registry.Server.missing_status?({:error, {:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], :nxdomain}]}})
(hex) lib/hex/registry/server.ex:355: Hex.Registry.Server.print_error/4
(hex) …
```
=> Add function so connection error does not result in FunctionClauseError

lib/hex/api/package.ex
An email address can contain invalid path uri components such as "+". If you
try to add or remove an email address with a "+" in it, you will get
back a 404.
=> Escape owner email address when adding or deleting an owner.

lib/mix/tasks/hex.search.ex
Fixes https://github.com/hexpm/hexpm/issues/571
New output (notice that I changed the `Version` column to `Latest` to avoid confusion
```
$ mix run -e 'Mix.Tasks.Hex.Search.run(["postgrex"])'
Package       Description                                            Latest      Stable  URL
postgrex      description                                            1.0.0-rc.1  0.13.3  https://hex.pm/packages/postgrex
ecto_network  Ecto types to support MACADDR and Network extensio...  0.6.0       0.6.0   https://hex.pm/packages/ecto_network
geo_postgis   PostGIS extension for Postgrex.                        1.0.0       1.0.0   https://hex.pm/packages/geo_postgis
posterize     erlang wrapper for the postgrex postgres client        0.13.3      0.13.3  https://hex.pm/packages/posterize
hstore        A …
```
=> Add a column to hex.search output showing stable version

CHANGELOG.md
This PR includes the following changes:
* Now the first header is a top level (`#`) header
* Starting bulleted lists at the beginning of the line
* Maximum line length is set to 80 columns
* Headers are now surrounded by blank lines
Also, I added a basic configuration for [mardownlint](https://github.com/DavidAnson/markdownlint), but it's not necessary to be included in the repo, just let me know what do you think?
=> Improve CHANGELOG style against mardownlint

lib/mix/tasks/hex.organization.ex
I didn't see anywhere that mentioned that this key allows read-only access, and prevents any write access. @ericmj confirmed in the #hex Slack channel that this is the case. This is an important security feature, and I think it would be helpful if it was documented.
Happy to alter the wording or format, just LMK.
=> Clarify repository key read-only access

lib/mix/tasks/hex.build.ex
This  PR will reject publishing packages defining `:system_env`.
For PR / discussion about `:system_env`, see: 
* https://github.com/elixir-lang/elixir/pull/6933#discussion_r145751510
* https://groups.google.com/forum/#!topic/elixir-lang-core/Lk08Vt0eRR0
=> Reject packages defining :system_env

lib/mix/tasks/hex.build.ex, test/mix/tasks/hex.build_test.exs
The current behavior allows to build the package, extracts its content in the `#{meta.name}-#{meta.version)-smoke` directory, retrieve the package dependencies, and then compiles the app. But, there are some things still missing, such as:
Any feedback is more than welcome.
Closes #436
=> Add mix hex.build --smoke

lib/mix/tasks/hex.build.ex, lib/mix/tasks/hex.publish.ex
This is just a tiny grammar change for the moduledocs of `hex.build.ex` and `hex.publish.ex`.
=> Make minor doc rewording to Mix.Tasks.Hex{Build,Publish}

lib/hex.ex, lib/hex/tar.ex, lib/mix/tasks/hex.build.ex, src/hex_erl_tar.erl, test/mix/tasks/hex.build_test.exs, test/support/release_samples.ex
Empty directories and symlinks are currently omitted when packaging the tar file. This PR allows empty directories and symlinks to be retained. 
This should be rebased once https://github.com/hexpm/hex/pull/440 lands
=> Preserve symlinks and empty directories in tar

lib/mix/tasks/hex.user.ex
The Mix task `mix hex.user test` is documented but it does not exist anymore.
=> Remove docs for old task: mix hex.user test

lib/hex/mix.ex, lib/hex/scm.ex, test/hex/mix_task_test.exs
Fixes elixir-lang/elixir#6570
Regression was introduced in https://github.com/hexpm/hex/pull/372
cc @josevalim
=> Populate managers when checking out dep

lib/hex/scm.ex, test/hex/mix_task_test.exs
Ref https://github.com/hexpm/hex/pull/426#issuecomment-340291244
Couldn't easily reproduce in the test suite. Manual repro is to:
1. resolve deps e.g. on Hex v0.15
2. update Hex to `master`
3. `rm -rf deps`
4. `mix deps.get`.
Note, on `master`, `rm -rf ~/.hex/cache.ets` fixes the problem.
=> Fix crash on managers check

lib/hex/scm.ex, lib/hex/shell.ex, lib/hex/state.ex
Ref https://github.com/hexpm/hex/issues/358#issuecomment-284712035
Ref https://github.com/hexpm/hex/issues/454
without MIX_DEBUG=1:
```
Resolving Hex dependencies...
Dependency resolution completed:
certifi 1.0.0
cowboy 1.1.2
cowlib 1.0.2
hackney 1.6.6 RETIRED!
(invalid)
idna 4.0.0
metrics 1.0.1
mime 1.1.0
mimerl 1.0.2
ranch 1.3.2
ssl_verify_fun 1.1.1
* Getting mime (Hex package)
* Getting cowboy (Hex package)
* Getting hackney (Hex package)
* Getting certifi (Hex package)
* Getting idna (Hex package)
* Getting metrics (Hex package)
* Getting mimerl (Hex package)
* Getting ssl_verify_fun (Hex package)
* Getting cowlib (Hex package)
* Getting ranch (Hex package)
```
with MIX_DEBUG=1:
```
** Running mix loadconfig (inside Foo.MixProject)
** Running mix deps.get (inside Foo.MixProject)
** …
```
=> Add Hex.Shell.debug/1 used with MIX_DEBUG=1

lib/mix/tasks/hex.retire.ex
This fixes a very small grammatical error in the documentation for the hex.retire mix task.
=> Fix grammatical error in documention in hex.retire

lib/hex/http.ex
The arguments on handle_redirect will never match (handle_response transforms the three item tuple into a different three item tuple), so the redirect logic will never be called.
I'd love to add a test for this, but the timeout, retry, and redirect methods are all private, and request directly calls httpc. I thought about adding an adapter, but wasn't sure if that'd add too much indirection.
=> Fix handle_redirect to match calling arguments

lib/hex.ex, lib/hex/scm.ex, lib/hex/tar.ex, lib/mix/tasks/hex.build.ex, lib/mix/tasks/hex.docs.ex, lib/mix/tasks/hex.publish.ex, test/hex/api_test.exs, test/hex/tar_test.exs, test/support/hexpm.ex
The goal is to define a public API that can be reused in other projects later on. A proper proposal to follow.
TODO:
=> Redesign Hex.Tar

lib/hex/tar.ex, mix-new.lock, mix.exs, test/hex/tar_properties_test.exs, test/hex/tar_test.exs
zlib can change the OS value in the gzip header. Instead build the header manually with 0 as OS value.
=> Make gzip reproducible

lib/mix/tasks/hex.info.ex
prints an alert when info is searched on a package version.
=> Alerts if a package has been retired in hex.info

lib/mix/tasks/hex.info.ex, test/mix/tasks/hex.info_test.exs, test/test_helper.exs
This depends on https://github.com/hexpm/hexpm/pull/616 to work, but will not break in the meantime.
If retirement data is returned with the API call, the versions that have been retired will be printed in yellow (see screenshots)
=> colors retired package yellow in mix hex.info PACKAGE

lib/mix/tasks/hex.search.ex
When searching for `mox` or `mock`, the cli returns an error:
```
❯ mix hex.search mock
** (FunctionClauseError) no function clause matching in String.split/3
The following arguments were given to String.split/3:
nil
"\n"
[trim: true]
(elixir) lib/string.ex:366: String.split/3
(hex) lib/mix/tasks/hex.search.ex:83: Mix.Tasks.Hex.Search.trim_heredoc/1
(hex) lib/mix/tasks/hex.search.ex:55: anonymous fn/1 in Mix.Tasks.Hex.Search.lookup_packages/1
(elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
(elixir) lib/enum.ex:1270: Enum."-map/2-lists^map/1-0-"/2
(hex) lib/mix/tasks/hex.search.ex:52: Mix.Tasks.Hex.Search.lookup_packages/1
(mix) lib/mix/task.ex:301: Mix.Task.run_task/3
(mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2
```
Other packages search works as expected:
```
❯ mix hex.search …
```
=> Prevent empty package["meta"]["description"] to crash search

lib/mix/tasks/hex.publish.ex, test/mix/tasks/hex.publish_test.exs
When publishing using the --organization flag, but not including organization in the mix.exs metadata, the output asks the user to confirm they are publishign to *public* repo hexpm.
Since that module is already setting the organization var using the flag first, then the metadata second, this PR uses that var instead of only looking at the metadata.
=> Fixes issue in hex.publish where it ignored the organization flag

lib/mix/tasks/hex.organization.ex
Whilst reading through documentation, I noticed "authentication" was spelled wrong.
=> Fixes misspelling in hex.organization documentation

lib/mix/tasks/hex.user.ex
"Revokal" sounds right, but it actually is not a word. The correct word is "Revocation"
=> Changes a grammatical error. Revokal is not a valid word.

lib/hex/tar.ex, src/hex_erl_tar.erl, src/hex_erl_tar.hrl, test/hex/tar_test.exs
Closes #474
The root cause was that FAT cannot store file timestamps before 1980-01-01 and we were trying to store 1970-01-01 for reproducible tars. Now we will store them as 2000-01-01 00:00:00.
This unfortunately means that tars created prior to this change will no longer be reproducible.
=>  Set atime/mtime/ctime to 2000-01-01 so that tar works on FAT

lib/mix/tasks/hex.docs.ex, test/mix/tasks/hex.docs_test.exs
Adds `mix hex.docs offline` and `mix hex.docs online` to clarify open task without using flags.
https://github.com/hexpm/hex/issues/502
There is a second component to this issue, and I might suggest it be handled in another pull request since the scope is quite different. @michalmuskala has started work on that functionality in the past. It sounds like it might be worth picking up where he left off.
=> Adds offline and online tasks to clarify open flags

lib/mix/tasks/hex.docs.ex, test/mix/tasks/hex.docs_test.exs
Took a crack at changing the local directory for docs from an organization.
It follows the convention set by packages and puts all docs in `HEX_HOME/docs/hexpm/package/release` or `HEX_HOME/docs/hexpm:org/package/release`
This will still leave previously downloaded packages orphaned. It may be worth adding some logic to the open function to look in the old location as well, but that may cause problems. If, for instance, I:
- have a public package downloaded now called "abc"
- and later I make a private package also named "abc"
- then I use `mix hex.docs fetch abc --organization org`
that would potentially  fall back into the docs/ directory to look for previously downloaded packages and find the public one. Then it would never actually download my private package docs.
It is hard to guess …
=> Adds organization to downloaded docs path

lib/mix/tasks/hex.build.ex, test/mix/tasks/hex.build_test.exs, test/support/release_samples.ex
As discussed in #506, this PR allows the option of `:exclude_patterns` in the Hex configs in order to list files you want to ignore in a package release.
This is my first Hex contribution so feedback and comments welcomed! Happy to fix things if this isn't the right approach.
=> Add :exclude_patterns to hex package options

lib/hex/resolver.ex
This will probably make the resolver slower when there are many
backtracks but the user most likely want the latest version of top-level
dependencies over transitive dependencies.
=> Backtrack children before parents

lib/mix/tasks/hex.docs.ex
Attempt to fix https://github.com/hexpm/hex/issues/523
Unit tests will also need to be updated to correctly match the system_cmd args, but I'll need a localhost postgres setup to be able to run the integration tests.  Leaving this here for now in case of early comments.
=> Fix hex.docs open on Windows

lib/mix/tasks/hex.repo.ex
I think this was an error in the documentation.
=> Fixes documentation in hex.repo task

lib/hex/crypto/encryption.ex, lib/mix/tasks/hex.ex
When a user is prompted to authenticate in the process of publishing a package, the authentication is already decrypted when it is passed to `Hex.Crypto.Encryption.decrypt/2`. This change recognizes that and passes the expected data back.
=> Prevents error when unauthenticated user authenticates while publishing

test/hex/mix_task_test.exs, test/hex/resolver_test.exs, test/mix/tasks/hex.docs_test.exs, test/mix/tasks/hex.outdated_test.exs, test/mix/tasks/hex.publish_test.exs, test/mix/tasks/hex.search_test.exs, test/support/case.ex, test/test_helper.exs
So first a fix to the test that was broken by the hex.docs open fix.
Second a fix to the resolver tests where Elixir thinks ANSI is unsupported.
There's still 9 test failures, all in the integration suite.  See https://github.com/hexpm/hex/issues/525 for details.
=> Windows tests

lib/mix/tasks/hex.info.ex
The documentation at the top of hex.info had a missing comma, and I tried to clarify the docs when package and version are given.
=> hex.info documentation fix

lib/hex/remote_converger.ex, lib/hex/resolver.ex, lib/hex/resolver/backtracks.ex, lib/hex/shell.ex, lib/mix/tasks/hex.publish.ex, test/hex/resolver/backtracks_test.exs, test/mix/tasks/hex.outdated_test.exs, test/mix/tasks/hex.publish_test.exs, test/mix/tasks/hex.search_test.exs, test/support/case.ex, test/test_helper.exs
I tried to use existing functions like IO.ANSI.format/2 to minimize changed code. The second arg for that function is whether or not to keep the ansi formatting. 
I am using a function that I put in Hex.Shell to make that false in test.
I am not sure this is the cleanest implementation, so feedback is welcomed.
=> Adds colors back into tests.

lib/hex/scm.ex
This is in response to https://github.com/hexpm/hex/issues/540
I thought we could offer a little more detail in the error message since it seems like it happens fairly regularly to people with poor connectivity. I would like to get feedback on the idea in general and the message itself.
The first commit is very red and bold.
The second commit puts the support message in regular text.
Also, does anyone know how to write a good test for this ?
First commit:
Second commit:
=> Show more detailed message when fetch times out

lib/hex/state.ex, lib/mix/tasks/hex.config.ex, lib/mix/tasks/hex.ex, lib/mix/tasks/hex.publish.ex, lib/mix/tasks/hex.user.ex, test/mix/tasks/hex.publish_test.exs, test/mix/tasks/hex.user_test.exs, test/support/case.ex
Fixes for https://github.com/hexpm/hex/issues/547
Adds a new task, `mix hex.user key --generate` that generates and outputs an unencrypted user key.
Allows including that key in ENV VAR `HEX_API_KEY` when publishing. That will authenticate the user and turn off the confirmation message.
Please give feedback if there is anything that doesnt look right or could be done better.
=> Adds new task to generate unencrypted key

lib/mix/tasks/hex.install.ex, test/mix/tasks/hex.install_test.exs
Fixes: https://github.com/hexpm/hex/issues/574
=> Raises an error if the arg passed is not a version

lib/hex/resolver.ex, lib/mix/tasks/hex.search.ex, mix.exs, test/hex/resolver_test.exs, test/support/case.ex
When we decide which backtrack to take, backtrack current failed request
or backtrack its parents, we do not know which will lead to the best
solution. Instead of picking one we will try both and after resolution
is finished we will try to find the best solutions based on heuristics
such as using highest version number.
Resolution failures will have the same performance, but successful
resolutions with backtracks will be slower because they need to try more
backtracking branches.
Closes #571.
=> Try all backtrack branches and select best solution

lib/hex.ex, lib/mix/tasks/hex.publish.ex, test/mix/tasks/hex.publish_test.exs, test/support/case.ex, test/support/release_samples.ex
This resolves part 2 of https://github.com/hexpm/hex/issues/591
I would like to submit part 1 in a different pull request since the issues are different enough.
=> Raise errors when top-level file in package matches semver pattern

lib/mix/tasks/hex.user.ex, test/mix/tasks/hex.user_test.exs
I noticed a bug with the reset_password local task today. It ends up saving the read_key as "New local password" (see gif)
This PR fixes that to save the read_key correctly and also updates the label and gives a success message after.
=> fixes issue saving write key when reseting local password

lib/mix/tasks/hex.publish.ex, test/mix/tasks/hex.publish_test.exs
Fixes: https://github.com/hexpm/hex/issues/607
Adds a `--dry-run` option to publish, publish docs, and publish package.
Includes unit test
Having the case statements in the else block seems a little awkward to me, if you guys have any better patterns or ideas please mention them. Also, feel free to edit the documentation message for the new flag.
=> Adds dry run option to publish tasks

lib/hex/remote_converger.ex
Fix for Issue #614 
Change the color of the status based on dep-status in deps.get output
New: green
Unchanged: default info color
Downgraded: default warn color (yellow)
Upgraded: green
=> print color of the status based on dep-status

lib/mix/tasks/hex.build.ex, test/mix/tasks/hex.build_test.exs
Path.wildcard("**") follows symlinks when collecting all of the files
under a path. This can lead to files in the tarball containing paths
with the symlink in them. If the directory corresponding to the symlink
hasn't been created, then the extraction will fail.
As an example, the "create with files" unit test now contains a symlink
in a directory. Without the fix, it fails like this:
```
1) test create with files (Mix.Tasks.Hex.BuildTest)
test/mix/tasks/hex.build_test.exs:42
** (MatchError) no match of right hand side value: {:error, :eexist}
code: in_tmp(fn ->
stacktrace:
test/mix/tasks/hex.build_test.exs:13: Mix.Tasks.Hex.BuildTest.extract/2
test/mix/tasks/hex.build_test.exs:69: anonymous fn/0 in Mix.Tasks.Hex.BuildTest."test create with files"/1
(elixir) lib/file.ex:1443: File.cd!/2 …
```
=> Don't follow symlinks when adding files to tarballs

lib/hex/api.ex, lib/hex/http.ex, lib/hex/state.ex, lib/mix/tasks/hex.config.ex, test/mix/tasks/hex.config_test.exs
Fixes #638 
There is a new module attr now for read keys. This was to accommodate the `api_key` but could also be useful if we want to show more attrs in read than we accept on write.
I added a fetch!/2 for the purpose of running transforms on the fetched value. It seemed like the best way given how we were using them. With the series of logical ORs, fetch! needs to return nil  sometimes, and multiplying nil * 1000 seemed like a bad idea :D
=> Changes hex.config to output all config settings and where they are derived from

lib/mix/tasks/hex.outdated.ex
In the past when an application dependency did not have any dependencies the
mix.lock file was generated as a 3-tuple:
```
"oauther": {:hex, :oauther, "1.0.2"},
```
While old, this is still valid. Currently `mix hex.outdated` is breaking if any
of the mix.lock contents use the 3-tuple format.
Here is an example of a mix.lock file that has a mix.lock that has an entry with
the old format:
https://github.com/ueberauth/ueberauth_example/blob/7e4d8b41c08d344a606a59554265d385555000a1/mix.lock
Running `mix hex.outdated` in that repository will give you the following error
without this change:
```
jason@jdesktop ~/d/f/ueberauth_example> mix hex.outdated
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
(elixir) lib/enum.ex:1: Enumerable.impl_for!/1
(elixir) …
```
=> Fix old-style mix.lock support

lib/hex/remote_converger.ex, lib/hex/version.ex, test/hex/version_test.exs
Fixes #676 
This will show a warning when the major version changes (up or down) on a >= 1.0 dependency or the minor version changes (up or down) on a < 1.0 dependency.
=> show a message when dependencies may contain breaking changes

lib/hex.ex, lib/mix/tasks/hex.ex, test/mix/tasks/hex_test.exs
This reverts commit dedd914c97a393c768bfa79e39787b6dc28a224e.
=> Bring back listing Hex tasks in `mix hex`

lib/hex/scm.ex, lib/hex/state.ex, lib/mix/tasks/hex.config.ex, lib/mix/tasks/hex.publish.ex, test/mix/tasks/hex.publish_test.exs
=> Change publish package message on non-default api_url

lib/mix/tasks/hex.publish.ex
I think this makes it slightly easier to understand the messaging about ownership that shows when publishing a new package.
I'm happy to make any desired changes.
=> clarify publish messaging around ownership

lib/mix/tasks/hex.outdated.ex, test/mix/tasks/hex.outdated_test.exs
Closes: #774 
Since Windows does not support the ANSI codes, giving instructions or docs that express meaning through color fails. This might also affect color-blind users. This change add more visual cues.
=> remove reliance on colors for hex.outdated

lib/hex/api/short_url.ex, lib/mix/tasks/hex.outdated.ex, test/mix/tasks/hex.outdated_test.exs
Closes #778 
When there are outdated deps that can be upgraded, build a list of the current version and the latest version. Then use the hexpm API to create a short link.
=> adds link to diffs page in footer of hex.outdated

lib/mix/tasks/hex.outdated.ex, test/mix/tasks/hex.outdated_test.exs
Closes #784 
This addresses the change to the outdated task.
@ericmj the outdated APP is very different. Was it your plan to have it act like the outdated task (while only showing output for that one dep?)
=> changes 2 columns into 1 status column with 3 possible values

lib/mix/tasks/hex.package.ex, test/mix/tasks/hex.package_test.exs
This makes `mix hex.package diff` more Unix shell friendly. With this, one can do `mix hex.package diff ex_doc 0.22.{0,1}`, which is expanded to `mix hex.package diff ex_doc 0.22.0 0.22.1` and is internally converted to `0.22.0..0.22.1`.
It would be nice to have #705 merged as well, although this PR would require minor updates to be fully compatible with that.
=> Make `mix hex.package diff` more CLI-friendly

lib/hex/http/ssl.ex, lib/hex/http/verify_hostname.ex
Hello everyone,
I already wrote one solution that I took over from the `mint` library to activate validation of wildcard certificates with the now stricter Erlang TLS handling in the issue here: https://github.com/hexpm/hex/issues/797
But I actually was able to find a better solution of using the wildcard hostname verification directly from the
[public_key Erlang module](https://github.com/erlang/otp/blob/9bca07b045b5fe6fe958f38b25585a0f50b326bb/lib/public_key/src/public_key.erl#L1113) that does to knowledge exactly the same.
Disclaimer: I did manual testing of this but wasn't really able to come up with how to actually test this.  Speaking of having a proper test setup that provides a server with wildcard certificate for its domain. If you know a way let me know. For now I can only …
=> Customize hostname check to allow also wildcard certificates

lib/mix/tasks/hex.publish.ex, test/mix/tasks/hex.publish_test.exs
It is no longer needed because we set the link header on the CDN.
=> Do not pass --canonical to docs task

lib/mix/tasks/hex.build.ex
Prevent Apple Desktop Services Store (`*.DS_Store`) files from slipping into Hex packages using the `exclude_patterns` package option introduced in https://github.com/hexpm/hex/pull/512.
Given that the issue affects a large number of popular Elixir packages (e.g., Ecto and gen_stage), [@josevalim proposed](https://github.com/elixir-ecto/ecto/pull/3221#issuecomment-581791936) that an overarching solution is to be preferred over a [case-by-case one](https://github.com/elixir-ecto/ecto/pull/3221).
This is an initial implementation based on vague requirements and I welcome suggestions on how to improve it.
=> Always add *.DS_Store to :exclude_patterns

lib/hex/dev.ex, lib/hex/registry/server.ex, lib/hex/repo.ex, lib/hex/scm.ex, lib/hex/tar.ex, lib/mix/tasks/hex.package.ex
Use tarball outer checksum to check if cache is fresh instead of using
etag to make conditional HTTP requests.
=> Use tarball outer checksum to check cache freshness

lib/mix/tasks/hex.outdated.ex, test/mix/tasks/hex.outdated_test.exs
Fixes #758
Currently, `hex.outdated` will exit with a non-zero exit code if there are any outdated dependencies.
However this is restrictive, as we do not always have time to update a major bump of our dependencies, but would still like to keep minor/bug fixes up to date.
With the introduction of this `--within-requirements`, this will be possible. By using the flag, `hex.outdated` will now only exit with a non-zero code if the upgrade is possible.
I couldn't figure out how to test it properly (not sure how to setup scenarios for outdated major/minor dependencies), so would love any guidance on that front.
=> Add `--within-requirements` flag

lib/hex/repo.ex, lib/hex/stdlib.ex, lib/mix/tasks/hex.repo.ex, test/hex/repo_test.exs, test/mix/tasks/hex.repo_test.exs
This allows Hex users to rely on the "/public_key" endpoint implemented by the [repositories](https://github.com/hexpm/specifications/blob/959f67a065959bc047baa2ccc4f0b4c5215dd53f/endpoints.md) to fetch the public key instead of doing it manually.
The option requires the user to know the fingerprint of the key in order to ensure more security. This prevents the key to be modified in transit.
It closes #801
Thanks!
=> Add `--fetch-public-key FINGERPRINT` to `mix hex.repo add`

lib/mix/tasks/hex.package.ex, test/mix/tasks/hex.package_test.exs
Closes #815
Seems like we were unpacking to verify the inner checksum. If we still want to do that, we could unpack, verify, then delete. I didnt feel like that would be the expected behaviour though
=> do not unpack tarball when flag is not passed

test/hex/mix_task_test.exs
Instead of sleep, we could do the following:
File.rm!("_build/test/lib/ecto/.mix/compile.fetch")
which is what we're most likely going to do in Elixir, but i'm worried we're leaking Mix too much.
cc @josevalim
=> Fix flaky divergereq test

lib/hex/http.ex, lib/hex/state.ex, lib/mix/tasks/hex.config.ex, test/mix/tasks/hex.config_test.exs
Add `no_proxy` variable to `set_options` instead of empty list
=> Support no_proxy environment variable

lib/mix/tasks/hex.sponsor.ex, test/mix/tasks/hex.sponsor_test.exs
This task can help people to find projects that are accepting
sponsorship. The task looks for a link in the package metadata
whose name is one of the following: sponsor, sponsorship,
funding, donate, donation.
=> Add hex.sponsor mix task

lib/mix/tasks/hex.sponsor.ex, test/mix/tasks/hex.sponsor_test.exs
It raises an error if running the "mix hex.sponsor" outside a Mix project.
=> Raise error for sponsor mix task when running outside Mix project

test/mix/tasks/hex.info_test.exs, test/mix/tasks/hex.organization_test.exs, test/mix/tasks/hex.outdated_test.exs, test/mix/tasks/hex.owner_test.exs, test/mix/tasks/hex.package_test.exs, test/mix/tasks/hex.publish_test.exs, test/mix/tasks/hex.retire_test.exs, test/mix/tasks/hex.search_test.exs, test/mix/tasks/hex.user_test.exs, test/support/case.ex
Fixes corruption of `~/.hex/hex.config` when running tests.
=> Fix leaking of test config into global config

lib/hex/http.ex
In our infrastructure we define no_proxy as `127.0.0.1, localhost, .acme.com, .acme.io` which works perfectly with every piece of software we use (curl and wget as an example).
During my experiments, I've found that wget does not support wildcards with asterisks and httpc does not support the alternative.
=> Add support for whitespaces and `.hostname` wildcards in no_proxy env var

lib/hex/config.ex, test/hex/config_test.exs
adds some unit testing to a function added for mix_xdg
I am not unit testing the when the mix_xdg flag is true because it will fail in < OTP19
I also found one other mistake in the last PR with the default arg
=> Add tests for mix xdg

lib/mix/tasks/hex.sponsor.ex
It is possible for a lock file to have entries which no longer exist in a mix project, as such the sponsor task will choke if it finds such an entry and tries to read in a hex_metadata.config file that does not exist.
- Adjust Mix.Task.Hex.Sponsor.read_metadata/2 (private) to check if the
path exists before attempt to invoke :file.consult/1 on the file.
- Closes #854
=> Gracefully handle missing hex metadata in sponsor task

lib/mix/tasks/hex.package.ex, test/mix/tasks/hex.package_test.exs
Closes #856 
I tried to move some functionality that was shared with hex.info into the utils module. If it doesn't make sense LMK.
=> Support fetch without version

lib/mix/tasks/hex.registry.ex, test/mix/tasks/hex.registry_test.exs
Closes https://github.com/hexpm/hex/issues/864
When trying to build a hex registry with a tarball which filename's version contains a hyphen, the command raises a `MatchError`. For example, given the following filename `jason-1.0.0-rc.1.tar`:
```elixir
$ mix hex.registry build public --name=acme --private-key=private_key.pem
** (MatchError) no match of right hand side value: ["jason", "1.0.0", "rc.1"]
lib/mix/tasks/hex.registry.ex:101: anonymous fn/1 in Mix.Tasks.Hex.Registry.build/3
(elixir 1.12.0-dev) lib/enum.ex:1318: anonymous fn/4 in Enum.group_by/3
(elixir 1.12.0-dev) lib/enum.ex:2331: Enum."-group_by/3-lists^foldl/2-0-"/3
lib/mix/tasks/hex.registry.ex:100: Mix.Tasks.Hex.Registry.build/3
(mix 1.12.0-dev) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
(mix 1.12.0-dev) …
```
=> Fix registry build crash on versions with hyphens

release_rebar.sh
This changes the construction of the CSV file so we keep the rebar build
for old Elixir versions (1.0.0) while being able to add it for new
Elixir versions (1.11.4).
=> Build of rebar3 and upload for specific Elixir versions

lib/hex/http.ex
The HTTP module didn't update SSL options when following a redirect.
That caused a handshake failure with do to `hostname_check_failed`. This passes the original `http_opts` through so that the SSL opts are recalculated for each redirect location.
For posterity, here was the original error I encountered when redirecting to a CloudFront URL:
```
- {:bad_cert, :hostname_check_failed}
** (Mix) Downloading http://localhost:4000/repo/tarballs/oban_pro-0.7.0.tar failed:
Request failed ({:failed_connect, [{:to_address, {'d2g9d86gzekkkn.cloudfront.net', 443}}, {:inet, [:inet], {:tls_alert, {:handshake_failure, 'TLS client: In state certify at ssl_handshake.erl:1768 generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,hostname_check_failed}'}}}]})
```
Note: There aren't any test changes …
=> Update ssl opts for host validation on redirect

lib/mix/tasks/hex.ex
Before this, entering a password "a", confirmation "b", and when trying again with "c" and confirming with "c" would write password "c", only to immediately overwrite it with password "a".
=> Encrypt the right password once.

lib/hex/state.ex, lib/mix/tasks/hex.config.ex, lib/mix/tasks/hex.outdated.ex, test/mix/tasks/hex.config_test.exs
- config will prevent hex from presenting shortened URLs (security measure?)
- adheres to ENV_VAR called HEX_NO_SHORT_URLS (boolean)
- config test updated
Closes: #880
=> Adds new config: no_short_urls

lib/hex/remote_converger.ex, lib/hex/scm.ex, lib/hex/sponsor.ex, lib/mix/tasks/hex.sponsor.ex, test/hex/mix_task_test.exs, test/setup_hexpm.exs
Closes #883
Was not sure where to add tests for it though, but I ran it locally and it printed like this:
=> Adding a tip to run `mix hex.sponsor` when a package that has a sponsor link is added or upgraded

.github/workflows/main.yml
For some reason its BEAM files are loaded when running mix test and they
are incompatible with some OTP versions we test on.
=> Remove rebar3 that is included in the base image

lib/mix/tasks/hex.repo.ex, test/mix/tasks/hex.repo_test.exs
This task can be useful if you CI or other tasks that require you to pass an explicit key, for example:
```
HEXPM_KEY=$(mix hex.repo get --auth-key) make build
```
This assumes you have previously authenticated with `mix hex.user auth`.
=> Add mix hex.repo get task

lib/hex/update_checker.ex, test/hex/update_checker_test.exs
Related with this issue https://github.com/hexpm/hex/issues/780
For context, if I'm not wrong, the problem is when there is a `check` operation, it has started, but it doesn't receive any `reply`. If this happens, the GenServer will timeout with the timeout defined in the API part of the GenServer.
In the solution I did:
1. Allow to initialize the state when you start the GenServer. I don't really like this, but is the only way that I found to be able to test and reproduce this bug. This is because I need a started=true and a reply=nil state.
2. Move the timeout from the API to the server.
3. Handle the timeout with `handle_info`.
=> Check hex timeout

lib/hex/mix.ex, lib/hex/remote_converger.ex, lib/hex/resolver.ex, lib/mix/tasks/hex.publish.ex, test/hex/mix_test.exs, test/support/resolver_helper.ex
Simplifies the overridden check and moves it out of the resolver to improve performance.
In initial testing it's a performance improvement of about 2-4x.
=> Add overridden_deps/1 and remove unnecessary resolver state

lib/hex/application.ex, lib/hex/http.ex, lib/hex/netrc.ex, lib/hex/netrc/cache.ex, lib/hex/netrc/parser.ex, test/hex/http_test.exs, test/hex/netrc/cache_test.exs, test/hex/netrc/parser_test.exs, test/hex/netrc_test.exs
This makes Hex check an optional `.netrc` file for login credentials whenever making HTTP requests.
In case no `authorization` header is present in the request (e.g. as a result of configuring an `auth_key` for the repository), Hex will try to locate a `.netrc` file by checking the `NETRC` environment variable and by checking the user's home directory. In case a file is found, Hex parses it and tries to read login credentials for the host to which the HTTP request is made.
The file format understood by Hex largely follows the [.netrc File Format of cURL](https://everything.curl.dev/usingcurl/netrc): it is a plain-text file with multiple records, each consisting of three lines:
* `machine` defines the host name to which the login credentials should apply
* `login` gives the username
* …
=> Add support for reading credentials from .netrc files

mix.exs
GitHub removed support for git:// protocol and only Elixir 1.1+ defaults
to https:// for :github deps. Explicitly use the https:// URL instead.
=> Fix deps on Elixir 1.0

lib/hex/package.ex, lib/mix/tasks/hex.build.ex, lib/mix/tasks/hex.publish.ex
This PR extracts the common docs part of `hex.publish` and `hex.build` tasks to a `Hex.Package` module.
It also adds a small change to the docs - 'see X below' now include links to the paragraphs
Fixes #941
=> Extract common docs to Hex.Package

lib/mix/tasks/hex.organization.ex
I just don't know how to express it correctly in english.
according to the doc (https://hexdocs.pm/hex/Mix.Tasks.Hex.Organization.html#module-generate-organization-key and https://hexdocs.pm/hex/Mix.Tasks.Hex.Organization.html#module-command-line-options), the permission to grant access to organization's repository is `repository` but I learnt the hard way that it has to be `repository:organization_name`.
So, the docs were misleading. I don't know if how I corrected them is the way to go
=> doc about `repository` permission is misleading

mix.exs
I noticed a bunch of warnings when running:
$ mix archive.install github hexpm/hex branch main
which look like this:
warning: Logger.error/1 defined in application :logger is used by the current application but the current application does not depend on :logger. To fix this, you must do one of:
1. If :logger is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs
2. If :logger is a dependency, make sure it is listed under "def deps" in your mix.exs
3. In case you don't want to add a requirement to :logger, you may optionally skip this warning by adding [xref: [exclude: [Logger]]] to your "def project" in mix.exs
Here are all the locations we use Logger:
lib/hex/parallel.ex:79: Hex.Parallel.handle_info/2
lib/hex/parallel.ex:88: …
=> Add :logger to :extra_applications

lib/hex/repo.ex, lib/hex/state.ex, lib/mix/tasks/hex.config.ex, lib/mix/tasks/hex.repo.ex, test/hex/repo_test.exs, test/mix/tasks/hex.config_test.exs
This commit:
- Renames `HEX_MIRROR` to `HEX_TRUSTED_MIRROR`
- Adds a new `HEX_MIRROR` which works like the old one but doesn't send the `authorization` header.
Closes #882.
=> Add `HEX_TRUSTED_MIRROR_URL` configuration

.github/workflows/main.yml, lib/hex/mix.ex, lib/hex/remote_converger.ex, lib/hex/solver.ex, lib/hex/solver/assignment.ex, lib/hex/solver/constraint.ex, lib/hex/solver/constraints/empty.ex, lib/hex/solver/constraints/impl.ex, lib/hex/solver/constraints/range.ex, lib/hex/solver/constraints/union.ex, lib/hex/solver/constraints/util.ex, lib/hex/solver/constraints/version.ex, lib/hex/solver/failure.ex, lib/hex/solver/incompatibility.ex, lib/hex/solver/package_lister.ex, lib/hex/solver/package_range.ex, lib/hex/solver/partial_solution.ex, lib/hex/solver/registry.ex, lib/hex/solver/requirement.ex, lib/hex/solver/solver.ex, lib/hex/solver/term.ex, lib/hex/solver/util.ex, lib/mix/tasks/hex.build.ex, test/hex/mix_task_test.exs, test/hex/mix_test.exs, test/mix/tasks/hex.build_test.exs, test/support/solver_helper.ex
Closes https://github.com/hexpm/hex/issues/972.
Before:
```
iex(1)> Mix.install([
...(1)>     {:phoenix, "~> 1.7.0"},
...(1)>     {:scrivener_html, github: "jaimeiniesta/scrivener_html", branch: "relax_phoenix_dep"},
...(1)> ])
* Getting scrivener_html (https://github.com/jaimeiniesta/scrivener_html.git - origin/relax_phoenix_dep)
remote: Enumerating objects: 831, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 831 (delta 2), reused 1 (delta 1), pack-reused 825
Resolving Hex dependencies...
Resolution completed in 0.021s
Because your app depends on phoenix empty which doesn't match any versions, version solving failed.
** (Mix.Error) Hex dependency resolution failed
```
After:
```
iex(1)> Mix.install([
...(1)>     {:phoenix, …
```
=> Solve with path and git deps

lib/hex/api.ex, lib/hex/http.ex, lib/hex/repo.ex, lib/mix/tasks/hex.publish.ex, test/hex/http_test.exs
Part of https://github.com/hexpm/hex/issues/738
=> Convert HTTP module into hex_core adapter

lib/hex/registry/server.ex, lib/hex/remote_converger.ex, test/support/hexpm.ex
Mix may still need the registry in fetcher finalization steps so we shouldn't close it.
=> Do not close registry server in post_converge

lib/mix/tasks/hex.organization.ex, test/mix/tasks/hex.organization_test.exs
It took me way too long to figure out that the person who set up the private hex.pm registry for me forgot to add billing credentials. I tried everything else because neither the web app nor the command line gave me a proper error. This PR hopefully changes this ;)
=> Improve logging of auth issues

lib/hex/mix.ex, lib/hex/remote_converger.ex, mix.exs, test/fixtures/umbrella/apps/my_app1/mix.exs, test/fixtures/umbrella/apps/my_app2/mix.exs, test/fixtures/umbrella/apps/my_app3/mix.exs, test/fixtures/umbrella/mix.exs, test/hex/mix_task_test.exs
=> Fix building requests from umbrella apps

lib/mix/tasks/hex.outdated.ex, test/mix/tasks/hex.outdated_test.exs
This PR aims to add a new flag as discussed in https://github.com/hexpm/hex/issues/1005 to sort results by their status (whether an update can be performed or not).
The PR doesn't aim to provide a generic "sort by column" functionality, as the default sort is already by package name, and sorting by the other remaining fields (current or available version numbers) doesn't seem very useful.
At the time of writing, this PR is rather exploratory in nature and is seeking general feedback on direction. Does a primitive solution like this suffice here, or are there important things I'm missing here? 
Tests are currently also missing, as I wanted to verify the general idea first. In any case, the primitive case seems to work:
```
juha@local:~/projects/elixir/hourchestra$ mix hex.outdated …
```
=> Provide --sort flag sorting outdated results by status

lib/mix/tasks/hex.publish.ex, test/mix/tasks/hex.publish_test.exs
=> Use docs output if set in project's config

lib/hex/scm.ex, test/hex/mix_task_test.exs
=> Warn on unknown dependency options

lib/hex/mix.ex, lib/hex/remote_converger.ex, test/fixtures/ecto_override/mix.exs, test/fixtures/umbrella_override/apps/my_app1/mix.exs, test/fixtures/umbrella_override/mix.exs, test/hex/mix_task_test.exs
=> Only filter non Hex overrides from requests

test/setup_hexpm.exs
…nto older hex versions for the hexpm matrix to pass
=> Valid licenses for hexpm integration tests

README.md
* https://hex.pm/ is using the description:
```
The package manager for the Erlang ecosystem
```
* `mix hex` outputs:
```
Hex is a package manager for the Erlang ecosystem.
```
So, maybe we should replace `Erlang VM` with `Erlang ecosystem`, which is a more appropriate term.
=> Make the description in README match the ones at other places

lib/mix/tasks/hex.docs.ex
Before this commit, if there was a timeout when download docs, an error
like this was printed:
```
$ mix hex.docs fetch elixir
Couldn't find docs for package with name elixir or version 1.18.0
```
With this commit, the error looks like this and the suggestion helped
me, at least:
```
$ mix hex.docs fetch elixir
Timed out trying to download docs. Try changing your timeout settings:
HEX_HTTP_TIMEOUT=120 mix hex.docs fetch elixir 1.18.0
$ HEX_HTTP_TIMEOUT=120 mix hex.docs fetch elixir 1.18.0
Docs fetched: /Users/fhunleth/.hex/docs/hexpm/elixir/1.18.0
```
=> Add help when docs download times out

.github/workflows/main.yml, lib/hex/mix.ex, lib/hex/remote_converger.ex, lib/hex/scm.ex, test/hex/remote_converger_test.exs
Example:
$ mix deps.get
Resolving Hex dependencies...
Resolution completed in 0.0s
Unchanged:
ecto 3.3.1
ecto_sql 3.3.2
ex_doc 0.1.0
postgrex 0.2.1
warning: the following deps set `warn_if_outdated: true` and are outdated:
* ecto 3.3.2 is available
* ecto_sql 3.3.3 is available
=> Support :warn_if_outdated in deps
