hexpm/hex

lib/mix/tasks/hex/publish.ex
=> Make warning about excluded dependencies more obvious

.travis.yml, test/test_helper.exs
Bug is likely a race condition in httpc.
=> Try fix test failures by slowing down tests

lib/hex.ex
Closes #79.
This PR alerts the user when non-standard config variables are set (`http_proxy`, `https_proxy`, `hex_api`, `hex_cdn`) in the following format:
```
$ HTTP_PROXY=http://proxy.server.com mix hex.info
Using http_proxy = http://proxy.server.com
...
```
/cc @josevalim
=> Log when non-standard config options are used

lib/mix/tasks/hex/docs.ex
Closes #84; Easy fix.
:page_facing_up: :memo:
=> Fixes the error on documentation push failure

lib/mix/tasks/hex/publish.ex, test/mix/tasks/hex/publish_test.exs
=> warn if files are missing

lib/hex/scm.ex, lib/hex/state.ex, lib/hex/tar.ex, lib/hex/utils.ex, lib/mix/tasks/hex/registry.ex, test/mix/tasks/hex/registry_test.exs
=> Introduce "mix hex.registry"

lib/hex/tar.ex, lib/mix/hex/build.ex, lib/mix/tasks/hex/build.ex, lib/mix/tasks/hex/publish.ex, test/mix/tasks/hex/build_test.exs
Add new `build` task to address #120.
Refactor `build` and `publish` tasks to use new `Mix.Hex.Build` module.
=> add build task

lib/hex/remote_converger.ex
Closes https://github.com/hexpm/hex/issues/133.
=> Correct missing registry warning

lib/mix/tasks/hex/outdated.ex
That way it works as expected in umbrellas
\cc @josevalim @ericmj
=> Make hex.outdated task recursive

lib/mix/tasks/hex/owner.ex
Related to https://github.com/hexpm/hex/issues/147 
Also, this requires the changes made in https://github.com/hexpm/hex_web/pull/183
=> add mix hex.owner packages task

lib/mix/tasks/hex/search.ex, test/mix/tasks/hex/search_test.exs
I tried implementing this, @ericmj  what do you think? 
https://github.com/hexpm/hex/issues/158
=> add version number for search output

test/mix/tasks/hex/build_test.exs, test/mix/tasks/hex/publish_test.exs, test/support/release.ex
had to setup the hex_web, maybe we should include that in the readme
https://github.com/hexpm/hex/issues/161
=> remove test duplication from build and publish task

lib/hex/mix.ex
Because dependencies with :only are filtered later in Elixir
v1.2, flatten deps would still find such dependencies in the
dep.deps parameter, causing the converger to fail later on.
This commit fixes the issue by only keeping dependencies that
were seen in the original list of deps.
=> Fix bug when umbrella child has dependency with :only

lib/hex/resolver/backtracks.ex
v0.10.0 added some simple merging of backtrack messages:
```
Conflict on phoenix 1.1.1
mix.exs: ~> 1.1.3
phoenix_live_reload 1.0.0: ~> 0.16 or ~> 1.0
Conflict on phoenix 1.1.2
mix.exs: ~> 1.1.3
phoenix_live_reload 1.0.0: ~> 0.16 or ~> 1.0
```
Could be merged to:
```
Conflict on phoenix 1.1.1, 1.1.2
mix.exs: ~> 1.1.3
phoenix_live_reload 1.0.0: ~> 0.16 or ~> 1.0
```
Then in v0.10.2 we improved the merging to also start merging backtrack messages with similar parents:
```
Conflict on phoenix 1.1.2
mix.exs: ~> 1.1.3
phoenix_live_reload 1.0.2: ~> 0.16 or ~> 1.0
Conflict on phoenix 1.1.2
mix.exs: ~> 1.1.3
phoenix_live_reload 1.0.3: ~> 0.16 or ~> 1.0
```
Could be merged to just:
```
Conflict on phoenix 1.1.2
mix.exs: ~> 1.1.3
phoenix_live_reload 1.0.2, 1.0.3: ~> 0.16 or ~> 1.0
```
Unfortunately …
=> Fix merging of overlapping parent and package versions

lib/hex/api.ex
Hey there,
Just started to play around with Elixir and was looking for some easy issues to work on. This is for issue #191.
Let me know if I should do anything different.
=> Append the OTP version to the user_agent function

test/support/case.ex
=> Fix some Elixir 1.4 warnings

lib/hex/tar.ex, test/hex/api_test.exs, test/support/hex_web.ex
=> Fix Hex.Tar.create usage

lib/hex/config.ex, lib/hex/remote_converger.ex, lib/hex/resolver.ex, lib/hex/resolver/backtracks.ex, lib/hex/version.ex, lib/mix/hex/utils.ex, test/hex/resolver/backtracks_test.exs, test/hex/resolver_test.exs
=> Mention overrides and pre-releases in resolver error

lib/mix/tasks/hex/publish.ex
=> Downcase checksum when a package is published

test/mix/tasks/hex/owner_test.exs
Add tests for `mix hex.owner packages` task.
=> [WIP] Add tests for mix hex.owner packages

lib/mix/tasks/hex/config.ex, test/mix/tasks/hex/config_test.exs
=> Add docs for mix.hex config KEY --delete

test/mix/tasks/hex/outdated_test.exs
@ericmj I'm trying to add a test for #276 (`hex.outdated` and `hex.outdated --all` in umbrella projects) and I'm getting the following error when I try `hex outdated --all`:
```
1) test umbrella projects (Mix.Tasks.Hex.OutdatedTest)
test/mix/tasks/hex/outdated_test.exs:190
No message matching {:mix_shell, :info, [^ex_doc]} after 0ms.
The following variables were pinned:
ex_doc = "\e[1mex_doc\e[0m      0.0.1\e[0m    \e[31m0.1.0\e[0m   \e[31m~> 0.0.1\e[0m     \e[0m"
Process mailbox:
{:mix_shell, :info, ["\e[4mDependency\e[0m  \e[4mCurrent\e[0m  \e[4mLatest\e[0m  \e[4mRequirement\e[0m  \e[0m"]}
{:mix_shell, :info, [""]}
{:mix_shell, :info, ["A green version in latest means you have the latest version of a given package. A green requirement means your current requirement matches the latest …
```
=> [WIP] Add test for hex.outdated in umbrella projects

test/support/case.ex
Just stumbled upon it while looking through the code :)
=> Removed unused in_fixture macro

lib/hex/state.ex, lib/mix/tasks/hex.ex, lib/mix/tasks/hex/config.ex
=> Clean up config & document it consistently

lib/hex/registry/server.ex
=> Do not check for updates when running in offline mode

README.md, test/support/hexpm.ex, test/test_helper.exs
=> Fix skipping integration tests

lib/mix/tasks/hex.publish.ex, test/mix/tasks/hex.publish_test.exs
=> [package_url] use api_url from config when displaying package url

lib/hex/tar.ex, src/hex_erl_tar.erl, test/mix/tasks/hex.build_test.exs, test/support/release_samples.ex
=> Preserve modes when building tarball

lib/mix/tasks/hex.docs.ex
Closes https://github.com/hexpm/hex/issues/388
=> Use Elixir current version to fetch documentation of built in applications

lib/hex/remote_converger.ex, test/hex/mix_task_test.exs
=> Improve error message when couldn't find matching version

lib/hex/option_parser.ex, lib/mix/tasks/hex.config.ex, lib/mix/tasks/hex.docs.ex, lib/mix/tasks/hex.info.ex, lib/mix/tasks/hex.install.ex, lib/mix/tasks/hex.organization.ex, lib/mix/tasks/hex.outdated.ex, lib/mix/tasks/hex.owner.ex, lib/mix/tasks/hex.publish.ex, lib/mix/tasks/hex.repo.ex, lib/mix/tasks/hex.retire.ex, lib/mix/tasks/hex.search.ex, lib/mix/tasks/hex.user.ex
=> Strict option parsing

lib/hex/tar.ex, lib/mix/tasks/hex.build.ex, test/hex/tar_test.exs, test/mix/tasks/hex.build_test.exs, test/support/release_samples.ex
=> Include metadata.config in deps

lib/hex.ex, lib/hex/server.ex, lib/hex/utils.ex, test/hex/mix_test.exs
=> Warn if detecting newer lock entry

lib/mix/tasks/hex.build.ex, test/mix/tasks/hex.build_test.exs, test/support/release_samples.ex
Fixes https://github.com/hexpm/hex/issues/439
=> include dot files when expanding file paths

lib/hex/api/package.ex, lib/mix/tasks/hex.search.ex, test/mix/tasks/hex.search_test.exs
=> Authenticate hex.search http requests

lib/hex.ex, lib/mix/tasks/hex.audit.ex, lib/mix/tasks/hex.publish.ex
=> Check deps on hex.publish & hex.audit

lib/mix/tasks/hex.publish.ex, test/mix/tasks/hex.publish_test.exs
=> Make repository more prominent in hex.publish

lib/hex/scm.ex
Simplifies hex output to format:
```
* Getting redix (Hex package)
Fetched package (https://repo.hex.pm/tarballs/redix-0.6.1.tar)
* Getting connection (Hex package)
Using locally cached package (path/to/local/connection-1.0.4.tar)
```
=> Simplify Hex output on deps.get #454

lib/hex/scm.ex, lib/hex/tar.ex, lib/mix/tasks/hex.build.ex, test/mix/tasks/hex.build_test.exs
=> Replace `--smoke` with `--unpack`

lib/mix/tasks/hex.outdated.ex, test/mix/tasks/hex.outdated_test.exs
=> List umbrella child top level deps in hex.outdated

lib/hex/remote_converger.ex, lib/hex/state.ex, lib/mix/tasks/hex.ex, lib/mix/tasks/hex.user.ex, test/mix/tasks/hex.publish_test.exs
When there is no authenticated user ask if they want to auth now instead of just telling them to auth.
=> Prompt for authenticating user

lib/mix/tasks/hex.owner.ex, test/mix/tasks/hex.owner_test.exs, test/support/hexpm.ex
Requires https://github.com/hexpm/hexpm/pull/612
=> Display package html url in `mix hex.owner packages`

lib/hex/version.ex, lib/mix/tasks/hex.info.ex, lib/mix/tasks/hex.search.ex, test/mix/tasks/hex.info_test.exs
=> Do not show retired releases in hex.info

lib/hex.ex, lib/hex/tar.ex, test/hex/tar_test.exs
=> Raise error when trying to create too big tarballs

lib/hex/api.ex, lib/hex/api/package.ex, lib/hex/api/release.ex, lib/mix/tasks/hex.info.ex, lib/mix/tasks/hex.search.ex, test/mix/tasks/hex.info_test.exs, test/mix/tasks/hex.search_test.exs, test/support/case.ex
Depends on https://github.com/hexpm/hexpm/pull/632
=> Fix --organization flags

lib/mix/tasks/hex.publish.ex
=> Documents the --no-confirm flag

lib/hex/scm.ex
Fixes crash when using Hex on a different endian than it was compiled on. Closes #469.
=> Remove regex usage

lib/mix/tasks/hex.outdated.ex, test/mix/tasks/hex.outdated_test.exs
=> Adds non-zero exit code when one or more dependencies is outdated

lib/hex/remote_converger.ex
=> Remove usages of Collectable with a non-empty list collectable

lib/hex/scm.ex, lib/hex/utils.ex, lib/mix/tasks/hex.docs.ex
=> Use - instead of : in paths on Windows

test/hex/mix_task_test.exs, test/mix/tasks/hex.config_test.exs, test/mix/tasks/hex.organization_test.exs, test/mix/tasks/hex.repo_test.exs, test/mix/tasks/hex.user_test.exs
=> System.cwd!/0 => File.cwd!/0

lib/mix/tasks/hex.publish.ex
Fixes #591 
- Refactor to create docs function
=> refactor create docs function

lib/mix/tasks/hex.build.ex, test/mix/tasks/hex.build_test.exs, test/support/release_samples.ex
Resolves https://github.com/hexpm/hex/issues/635
=> Error with a descriptive msg when building a package with git deps

lib/hex.ex, lib/hex/http.ex, lib/hex/http/ssl.ex, lib/hex/registry/server.ex, lib/hex/repo.ex, lib/hex/scm.ex, lib/hex/state.ex, lib/hex/update_checker.ex, test/hex/resolver/backtracks_test.exs, test/hex/resolver_test.exs, test/support/case.ex, test/test_helper.exs
First step of https://github.com/hexpm/hex/issues/638.
=> Store source of value in Hex.State

lib/mix/tasks/hex.info.ex, test/mix/tasks/hex.info_test.exs
=> Print publisher info in Hex.Info.print_release/3

lib/mix/tasks/hex.config.ex, test/mix/tasks/hex.config_test.exs
=> Adds support for mirror_url config

lib/hex/state.ex, lib/mix/tasks/hex.config.ex, test/mix/tasks/hex.config_test.exs, test/support/release_samples.ex
=> Add per-project Hex configuration

lib/mix/tasks/hex.build.ex, test/mix/tasks/hex.build_test.exs
=> Add saved to location after build

lib/hex/state.ex, lib/mix/subtasks.ex, lib/mix/task_description.ex, lib/mix/tasks/hex.audit.ex, lib/mix/tasks/hex.build.ex, lib/mix/tasks/hex.config.ex, lib/mix/tasks/hex.docs.ex, lib/mix/tasks/hex.ex, lib/mix/tasks/hex.info.ex, lib/mix/tasks/hex.install.ex, lib/mix/tasks/hex.organization.ex, lib/mix/tasks/hex.outdated.ex, lib/mix/tasks/hex.owner.ex, lib/mix/tasks/hex.publish.ex, lib/mix/tasks/hex.repo.ex, lib/mix/tasks/hex.retire.ex, lib/mix/tasks/hex.search.ex, lib/mix/tasks/hex.user.ex
Issue #678 
I don't have update the unit test as the originally unit test for hex.ex doesn't cover the task display.
=> Adding subtask description

lib/mix/tasks/hex.package.ex, test/mix/tasks/hex.package_test.exs, test/support/case.ex
Issue #632 
Adding the unit tests based on another pull request.
=>  Add initial implementation of Mix.Tasks.Hex.Package 

lib/hex/mix.ex, lib/mix/tasks/hex.outdated.ex, test/mix/tasks/hex.outdated_test.exs
Fixes #686 
@ericmj it seems you have a good test setup for this issue (possibly better than mine.) If possible, can you play around with this to make sure I didnt cause some unexpected issue?
Also, interested in feedback on the output formatting.
=> Hex outdated app for umbrella

lib/hex/api/package.ex, lib/mix/tasks/hex.config.ex, lib/mix/tasks/hex.organization.ex, lib/mix/tasks/hex.owner.ex, lib/mix/tasks/hex.publish.ex, test/hex/api_test.exs, test/mix/tasks/hex.organization_test.exs, test/mix/tasks/hex.owner_test.exs, test/mix/tasks/hex.publish_test.exs, test/mix/tasks/hex.search_test.exs, test/support/case.ex, test/test_helper.exs
=> Add mix hex.owner transfer task

lib/hex/state.ex, test/mix/tasks/hex.publish_test.exs
Closes https://github.com/hexpm/hex/issues/683.
=> Print error message on invalid config

lib/hex/scm.ex, lib/hex/state.ex, lib/mix/tasks/hex.owner.ex, lib/mix/tasks/hex.package.ex, lib/mix/tasks/hex.publish.ex, test/hex/api_test.exs, test/mix/tasks/hex.organization_test.exs, test/mix/tasks/hex.package_test.exs, test/mix/tasks/hex.publish_test.exs
Ref: #632
Demo: https://asciinema.org/a/249929
=> Add `mix hex.package diff VERSION1..VERSION2`

lib/hex/shell.ex
=> Sets ansi_enabled? based on setting in IO for non-test envs

lib/mix/tasks/hex.package.ex, test/mix/tasks/hex.package_test.exs
Issue #632. 
Adding the support for fetching the tarball to user defined destination
=> Fetch with custom path

lib/hex.ex, test/hex/api_test.exs, test/mix/tasks/hex.build_test.exs, test/mix/tasks/hex.package_test.exs, test/mix/tasks/hex.publish_test.exs, test/support/release_samples.ex
=> Raises when the metadata files list is empty

lib/mix/tasks/hex.docs.ex, test/mix/tasks/hex.docs_test.exs, test/support/case.ex
=> Fetch latest

lib/hex/scm.ex, test/hex/mix_task_test.exs
=> Handle old manifest files

src/mix_hex_core.hrl, src/mix_hex_erl_tar.erl, src/mix_hex_erl_tar.hrl, src/mix_hex_filename.erl, src/mix_hex_pb_package.erl, src/mix_hex_pb_signed.erl, src/mix_hex_registry.erl, src/mix_hex_tarball.erl, src/mix_safe_erl_term.xrl
Fixes tarball file extraction through symlinks
=> Vendor hex_core v0.6.8

lib/hex/api/release.ex, lib/mix/tasks/hex.publish.ex
This is the CLI side of https://github.com/hexpm/hexpm/issues/855
It should be considered a WIP for now.
=> adds replace option for publish

lib/hex/repo.ex, lib/hex/server.ex, test/hex/server_test.exs
=> Fix Hex.Server.should_warn_registry_version?/0

test/fixtures/ecto_3_3_1/mix.exs, test/fixtures/ecto_3_3_2/mix.exs, test/fixtures/ecto_enum_1_4_0/mix.exs, test/fixtures/ecto_sql_3_3_2/mix.exs, test/fixtures/ecto_sql_3_3_3/mix.exs, test/fixtures/has_hex_dep/mix.exs, test/hex/api_test.exs, test/hex/mix_task_test.exs, test/mix/tasks/hex.audit_test.exs, test/mix/tasks/hex.docs_test.exs, test/mix/tasks/hex.owner_test.exs, test/mix/tasks/hex.retire_test.exs, test/support/hexpm.ex, test/test_helper.exs
See https://github.com/elixir-lang/elixir/pull/9811.
=> Add test for :divergedreq

lib/mix/tasks/hex.docs.ex, test/mix/tasks/hex.docs_test.exs, test/support/case.ex
=> supports --epub option for opening epub version of docs offline

lib/mix/tasks/hex.info.ex, test/mix/tasks/hex.info_test.exs
This PR adds the locked version of the package, if it is installed in the current mix project.
If it is installed:
```bash
~/Development/hexpm [master] λ mix hex.info cowboy
Small, fast, modular HTTP server.
Config: {:cowboy, "~> 2.7"}
Locked version: 2.6.3
Releases: 2.7.0, 2.6.3, 2.6.2 (retired), 2.6.1, 2.6.0, 2.5.0, 2.4.0, 2.3.0, ...
Licenses: ISC
Links:
GitHub: https://github.com/ninenines/cowboy
```
If it is *not* installed:
```bash
~/Development/hexpm [master] λ mix hex.info meetup
Elixir wrapper for the Meetup.com public API.
Config: {:meetup, "~> 0.1.2"}
Releases: 0.1.2, 0.1.1, 0.1.0
Licenses: GPL 3.0
Links:
GitHub: https://github.com/supersimple/meetup
```
Thank you to @supersimple for pair-programming with me on this one!
=> Add locked version to `mix hex.info <package>`

lib/hex/config.ex, lib/hex/registry/server.ex, lib/hex/scm.ex, lib/hex/state.ex, lib/mix/tasks/hex.config.ex, lib/mix/tasks/hex.docs.ex, test/hex/mix_task_test.exs, test/mix/tasks/hex.audit_test.exs, test/mix/tasks/hex.build_test.exs, test/mix/tasks/hex.config_test.exs, test/mix/tasks/hex.docs_test.exs, test/mix/tasks/hex.info_test.exs, test/mix/tasks/hex.repo_test.exs
=> follow xdg base dir specification

lib/mix/tasks/hex.package.ex, test/mix/tasks/hex.package_test.exs
=> feat: allow to fetch packages from self-hosted Hex instances

CHANGELOG.md, lib/hex.ex, lib/mix/tasks/hex.config.ex, lib/mix/tasks/hex.info.ex, lib/mix/tasks/hex.organization.ex, lib/mix/tasks/hex.owner.ex, lib/mix/tasks/hex.package.ex, lib/mix/tasks/hex.publish.ex, lib/mix/tasks/hex.user.ex, test/mix/tasks/hex.owner_test.exs
Update spelling issues through `aspell`.
=> Fix spelling errors

lib/mix/tasks/hex.info.ex, test/mix/tasks/hex.info_test.exs
=> non-zero exit when package or release are not found

lib/mix/tasks/hex.registry.ex, src/mix_hex_http.erl, src/mix_hex_http_httpc.erl, src/mix_hex_repo.erl, src/mix_hex_tarball.erl, test/mix/tasks/hex.registry_test.exs, vendor_hex_core.sh
=> Add `mix hex.registry` build

lib/mix/tasks/hex.install.ex
=> Fix mix hex.install

lib/hex/scm.ex
Closes #821
I was able to re-produce the above mentioned issue by doing the following:
```
foo$ mix hex.publish package
bar$ mix deps.get
foo$ echo "# foo" >> mix.exs # so that checksum changes
foo$ mix hex.publish package --replace
bar$ mix deps.get
```
The workaround for folks is to remove the cached package: `rm ~/.hex/packages/<repo>/<package>-<version>.tar`.
I'm not sure if doing this rather than failing creates some sort of attack vector, so another option would be to tell folks to manually remove the cached package tarball.
=> Re-fetch package if registry checksum changed

lib/hex/config.ex, lib/hex/http.ex, lib/hex/state.ex
@wojtekmach @ericmj I think this is what we wanted to do, but the issue wasn't very clear. If you have more details, please comment and I will continue to work on it. Thanks.
=> replaces xdg_config_home and xdg_cache_home with mix_xdg

lib/hex/config.ex, lib/hex/state.ex, test/hex/config_test.exs
Closes #850
Paired with my dearest @supersimple on this one
=> Show MIX_XDG and HEX_HOME as sources on mix hex.config

lib/mix/tasks/hex.build.ex, lib/mix/tasks/hex.config.ex, lib/mix/tasks/hex.docs.ex, lib/mix/tasks/hex.ex, lib/mix/tasks/hex.info.ex, lib/mix/tasks/hex.organization.ex, lib/mix/tasks/hex.outdated.ex, lib/mix/tasks/hex.owner.ex, lib/mix/tasks/hex.package.ex, lib/mix/tasks/hex.publish.ex, lib/mix/tasks/hex.registry.ex, lib/mix/tasks/hex.repo.ex, lib/mix/tasks/hex.retire.ex, lib/mix/tasks/hex.search.ex, lib/mix/tasks/hex.sponsor.ex, lib/mix/tasks/hex.user.ex
See https://github.com/elixir-lang/elixir/pull/11162#issue-701210754 for more context on the change.
=> Update Mix task docs

mix.exs
Follow-up on https://github.com/hexpm/hex/pull/943.
=> Bump elixir requirement to ~> 1.5

.github/workflows/main.yml, lib/hex/parallel.ex, lib/hex/stdlib.ex, mix.exs, test/support/hexpm.ex
Closes https://github.com/hexpm/hex/issues/976.
=> Remove :ssh application dependency

lib/hex/repo.ex, test/hex/repo_test.exs
=> Fix recursive Hex.State call during application start

lib/mix/tasks/hex.organization.ex, test/mix/tasks/hex.organization_test.exs
=> Set exit status on organization.auth failure

lib/mix/tasks/hex.publish.ex, test/mix/tasks/hex.publish_test.exs
=> Improve error message when trying to publish existing package with permissions

test/support/release_samples.ex
Sorry, I missed these in the last PR.
=> Fixes licenses for the release samples
